"""tablas iniciales

Revision ID: 026f9d2d85a5
Revises: 
Create Date: 2026-06-23 19:00:48.106975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026f9d2d85a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('serial', sa.String(length=100), nullable=True),
    sa.Column('departamento', sa.String(length=100), nullable=False),
    sa.Column('tipo_disco', sa.String(length=20), nullable=False),
    sa.Column('capacidad_disco', sa.Integer(), nullable=True),
    sa.Column('ram_gb', sa.Integer(), nullable=False),
    sa.Column('sistema_operativo', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_registro', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('dias_sin_mtto', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.String(length=20), nullable=False),
    sa.Column('fecha_generada', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipo_id')
    )
    op.create_table('mantenimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('actividades', sa.Text(), nullable=False),
    sa.Column('tecnico_responsable', sa.String(length=100), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mantenimientos')
    op.drop_table('alertas')
    op.drop_table('equipos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
